### ISSUE TITLE
What about turning this project into a "real" awesome list?

### ISSUE THREAD

**Issue by fkromer** [sspaeti-com/awesome-dagster#1]
Today **dagster** is one of the leading data orchestration platforms out there. What about turning this project into an awesome list compatible with [`sindresorhus/awesome`](https://github.com/sindresorhus/awesome/blob/main/awesome.md)?

**Comment by sspaeti** [comment]
Thanks @fkromer. I thought I did, but I didn't really maintain anymore. Please see now the official dagster-repo at https://github.com/dagster-io/awesome-dagster.
