### ISSUE TITLE
Combine forces with `dagster-io/dagster-awesome`

### ISSUE THREAD

**Issue by cmpadden** [sspaeti-com/awesome-dagster#2]
Hi @sspaeti - I wanted to thank you for starting this `awesome-dagster` project. We are interested in helping build a list of resources like this over at Dagster too, and have since created our own version: https://github.com/dagster-io/awesome-dagster.

Thank you for the inspiration, and you're welcome to make contributions on the repo in the `dagster-io` organization if you'd like. We don't mind having two lists, but wanted to let you know that you're welcome over in the other repo too.

Cheers!

**Comment by sspaeti** [comment]
@cmpadden Thanks so much for the info. I moved the relevant content over to yours in this PR: https://github.com/dagster-io/awesome-dagster/pull/10. Feel free to strip away if some are too old. 

I also added a note to this repo to check out the official dagster repo. I might archive this repo later. For now, I still have some resources ( like delta-lake or druid) that are too old to move, but also might add some value for some who find this here.
